zeros

The zeros tool returns a new array with a given shape and type filled with 's.|

In [2]:
import numpy

print(numpy.zeros((1,2)))
print(numpy.zeros((1,2), dtype = numpy.int))

[[0. 0.]]
[[0 0]]


ones

The ones tool returns a new array with a given shape and type filled with 's.

In [5]:
import numpy

print(numpy.ones((1,2)))
print(numpy.ones((1,2,3), dtype = numpy.int))

[[1. 1.]]
[[[1 1 1]
  [1 1 1]]]


ZEROS AND ONES

In [21]:
import numpy

N = list(map(int,input().split()))
print(numpy.zeros(tuple(N), dtype = numpy.int))
print(numpy.ones(tuple(N), dtype = numpy.int))

 3 3 3


[3, 3, 3]
(3, 3, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
