identity

The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.

In [35]:
import numpy
print(numpy.identity(3)) #3 is for  dimension 3 X 3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


eye

The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

In [3]:
import numpy
print(numpy.eye(8, 7, k = 1)) # 8 X 7 Dimensional array with first upper diagonal 1
print(numpy.eye(8, 7, k = -2))# 8 X 7 Dimensional array with second lower diagonal 1.

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [37]:
import numpy

n, m = map(int,input().split())
print(numpy.eye(n, k=0))

 3 3


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
import numpy

print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

 3 3


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Mathematical calculations

In [ ]:
import numpy

print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))