In [8]:
import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print(a + b)                 #[  6.   8.  10.  12.]
print(numpy.add(a, b))           #[  6.   8.  10.  12.]

print(a - b)                     #[-4. -4. -4. -4.]
print(numpy.subtract(a, b))      #[-4. -4. -4. -4.]

print(a * b)                     #[  5.  12.  21.  32.]
print(numpy.multiply(a, b))      #[  5.  12.  21.  32.]

print(a // b)                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print(numpy.divide(a, b))        #[ 0.2         0.33333333  0.42857143  0.5       ]

print(a % b)                     #[ 1.  2.  3.  4.]
print(numpy.mod(a, b))           #[ 1.  2.  3.  4.]

print(a**b)                     #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print(numpy.power(a, b))         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]

[ 6.  8. 10. 12.]
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[ 5. 12. 21. 32.]
[0. 0. 0. 0.]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [50]:
import numpy

n, m = map(int, input().split())
a=numpy.zeros((n,m),int)
b=numpy.zeros((n,m),int)
for i in range(n):
    a[i] = numpy.array(input().split(),int)
for i in range(n):
    b[i] = numpy.array(input().split(),int)
print(numpy.add(a, b))
print(numpy.subtract(a, b))
print(numpy.multiply(a, b))
print(a // b)
print(numpy.mod(a, b))
print(numpy.power(a, b))

 2 2
 1 2
 3 4
 2 2
 1 2


[[3 4]
 [4 6]]
[[-1  0]
 [ 2  2]]
[[2 4]
 [3 8]]
[[0 1]
 [3 2]]
[[1 0]
 [0 0]]
[[ 1  4]
 [ 3 16]]


sum

The sum tool returns the sum of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)                   #Output : 10
By default, the axis value is None. Therefore, it performs a sum over all the dimensions of the input array.

prod

The prod tool returns the product of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]
print numpy.prod(my_array, axis = None)         #Output : 24
print numpy.prod(my_array)                      #Output : 24
By default, the axis value is None. Therefore, it performs the product over all the dimensions of the input array.

In [58]:
import numpy

n, m = map(int, input().split())
a=numpy.zeros((n,m),int)
for i in range(n):
    a[i] = numpy.array(input().split(),int)
b = numpy.sum(a, axis = 0)
print(numpy.prod(b))

 2 2
 1 2
 3 4


24


min

The tool min returns the minimum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]
print numpy.min(my_array, axis = None)      #Output : 0
print numpy.min(my_array)                   #Output : 0
By default, the axis value is None. Therefore, it finds the minimum over all the dimensions of the input array.

max

The tool max returns the maximum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]
print numpy.max(my_array, axis = None)      #Output : 7
print numpy.max(my_array)                   #Output : 7
By default, the axis value is None. Therefore, it finds the maximum over all the dimensions of the input array.

In [60]:
import numpy

n, m = map(int, input().split())
a=numpy.zeros((n,m),int)
for i in range(n):
    a[i] = numpy.array(input().split(),int)
b = numpy.min(a, axis = 1)
print(numpy.max(b))

 4 2
 2 5
 3 7
 1 3
 4 0


3
