dot

The dot tool returns the dot product of two arrays.

In [9]:
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print(numpy.dot(A, B))       #Output : 11

11


cross

The cross tool returns the cross product of two arrays.

In [10]:
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print(numpy.cross(A, B))     #Output : -2

-2


In [11]:
import numpy as np
# two dimensional arrays
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[1,2],[3,4]])
m3 = np.dot(m1,m2) 
print(m3) 

# three dimensional arrays
m1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
m2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
m3 = np.dot(m1,m2) 
print(m3)

[[ 7 10]
 [15 22]]
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [ ]:
import numpy
n = int(input())
a = [list(map(int, input().split())) for x in range(n)]
b = [list(map(int, input().split())) for x in range(n)]
print(numpy.dot(a, b))